### ISSUE TITLE
Gebruik van "GetypeerdeString" als verwacht type in Applicatieprofielen

### ISSUE THREAD

**Issue by jensscheerlinck** [Informatievlaanderen/Data.Vlaanderen.be#10]
In applicatieprofielen waar gebruik gemaakt wordt van "GetypeerdeString" ([Persoon](http://data.vlaanderen.be/doc/applicatieprofiel/persoon), [Organisatie](http://data.vlaanderen.be/doc/applicatieprofiel/organisatie) en [Generiek](http://data.vlaanderen.be/doc/applicatieprofiel/generiek#GetypeerdeString)) als verwacht type voor een eigenschap wordt verwezen naar **http://www.w3.org/2000/01/rdf-schema#Literal** in plaats van http://data.vlaanderen.be/doc/applicatieprofiel/generiek#GetypeerdeString (GetypeerdeString komt niet voor in het generiek vocabularium).

In het Applicatieprofiel Generiek Basis is voor het datatype GetypeerdeString de eigenschap "string" opgenomen (verwacht type: **http://www.w3.org/2000/01/rdf-schema#Literal**). Deze eigenschap heeft als URI http://data.vlaanderen.be/ns/generiek#string maar staat niet gedefinieerd in het generiek vocabularium.

**Comment by DieterDePaepe** [comment]
GetypeerdeString was ingevoerd om het model ook bruikbaar te hebben buiten een RDF context. In RDF context is het bedoeld om een Literal te gebruiken.

Fout is dus dat GetypeerdeString staat uitgewerkt in het profiel.
