### ISSUE TITLE
Overerving van Object

### ISSUE THREAD

**Issue by GeertThijs** [Informatievlaanderen/Data.Vlaanderen.be#104]
Die overerving is bedoeld om aan te geven dat de klasse een authentiek object is. Zie ook issue #103. Echter wordt bij omzetting naar RDF deze overerving genegeerd en omgezet in een overerving van Resource.

**Comment by GeertThijs** [comment]
Hier zouden we kunnen argumenteren dat de kenmerken die we voorzien voor een Object (identificator, wordtBeschrevendoor, via wordtBeschrevenDoor:generatie, invalidatie) ook gemapt zijn op kenmerken van een Resource. In het AP wordt dit dan wel explicieter aangegeven.

**Comment by jensscheerlinck** [comment]
This issue was moved to Informatievlaanderen/OSLO-Discussion#163
