### ISSUE TITLE
Inconsistenties Persoon Vocabularium & AP

### ISSUE THREAD

**Issue by jensscheerlinck** [Informatievlaanderen/Data.Vlaanderen.be#11]
- Het attribuut 'adelijke titel' wordt weergegeven in het overzichtsdiagram van Applicatieprofiel Persoon Basis maar wordt niet vermeld als eigenschap (ook niet in het vocabularium)
- In het Applicatieprofiel Persoon Basis heeft het attribuut 'datumVanAfstamming' als type 'GetypeerdeString' (http://www.w3.org/2000/01/rdf-schema#Literal). Is er een reden/use case om hier niet te kiezen voor http://www.w3.org/2001/XMLSchema#date? Zie ook #10
- In het Vocabularium Persoon zijn volgende eigenschappen opgelijst: 
	- http://data.vlaanderen.be/ns/persoon#Staatsburgerschap.binnenJurisdictie
	- http://data.vlaanderen.be/ns/persoon#Inwonerschap.binnenJurisdictie
  Deze komen niet voor in het overzicht van eigenschappen noch in het Applicatieprofiel Persoon Basis en lijken ook overbodig.

**Comment by DieterDePaepe** [comment]
- Adelijke titel is niet uitgewerkt in OSLO, de fout is dus dat het op de figuur staat.
- Ja, om ook onvolledige data toe te laten (bvb xsd:gYear)
- De attributen komen voor in de lijst in het vocabularium, maar niet bij het applicatie profiel (waar ze wel zouden moeten staan). Het attribuut is nodig om de link te leggen tussen het inwonerschap en de bijhorende jurisdictie indien de persoon er meerdere heeft.
