### ISSUE TITLE
Hernoem 'gebouwstatus' en 'gebouweenheidstatus' naar 'status'

### ISSUE THREAD

**Issue by rubcap** [Informatievlaanderen/Data.Vlaanderen.be#116]
**Motivatie:** 
uniformiteit met het vocabularium 'Adres', waarin ook een veld 'status' voorkomt bij 'Straatnaam' en 'Adres'.

**Comment by jensscheerlinck** [comment]
This issue was moved to Informatievlaanderen/OSLO-Discussion#162
