### ISSUE TITLE
Splits '2DGebouwgeometrie.specificatie' op in een horizontale/verticale specificatie

### ISSUE THREAD

**Issue by rubcap** [Informatievlaanderen/Data.Vlaanderen.be#117]
**Context:**
Vocabularium 'Gebouw': ‘specificatie’ in het datatype '2DGebouwgeometrie' verwijst naar codelijst ‘geometriespecificatie’ (ook gebruikt voor Adres.positie.GeografischePositie) en zou hier dus waarde ‘gebouw’ hebben: geen meerwaarde om nog eens aan te geven dat de geometrie een gebouw betreft.

**Voorstel:**
Vervangen door ‘XYspecificatie’ (verplicht) en ‘Zspecificatie’ (optioneel, enkel relevant indien ook hoogte-attribuut aanwezig is), die aangeven welk deel van het gebouw werd opgemeten.

'XYspecificatie' kan gebaseerd worden op 'HorizontalGeometryReference' in de 'INSPIRE Building'-specificatie, 'Zspecificatie' op 'ElevationReferenceValue'. Over de naamgeving van deze attributen kan nog gediscussieerd worden uiteraard.

**Motivatie:**
Codelijst ‘geometriespecificatie’ verwijst dan naar objecten, 'XY/Zspecificatie’ naar onderdelen van objecten. Nuttig voor partijen die andere geometrie beheren/uitwisselen (bv. Basiskaart Vlaanderen biedt 'footprint' aan vs. Gebouwenregister biedt 'aboveGroundEnvelope' aan).

**Comment by rubcap** [comment]
![xy_z_specificatie](https://user-images.githubusercontent.com/26146350/42093181-baf88be6-7bab-11e8-8c02-afa1b5a74cff.png)

**Comment by jensscheerlinck** [comment]
This issue was moved to Informatievlaanderen/OSLO-Discussion#161
