### ISSUE TITLE
Opportuun om codelijsten 'geometriemethode' samen te voegen?

### ISSUE THREAD

**Issue by rubcap** [Informatievlaanderen/Data.Vlaanderen.be#118]
**Context:**
Er is een aparte codelijst voor geometriemethode, binnen de datatypes 'GeografischePositie' (vocabularium Adres) resp. '2DGebouwgeometrie' (vocabularium Gebouw). 

**Voorstel:**
Niet één codelijst voor puntgeometrieën en één voor 2Dgeometrieën, maar één generiekere (gedeelde) codelijst.

**Motivatie:**
Semantisch bestaat er tussen deze codelijsten voldoende overlap om deze samen te voegen?

**Comment by rubcap** [comment]
![codelijst_geometriemethode](https://user-images.githubusercontent.com/26146350/42094044-c382cf8a-7bae-11e8-921e-23c3e56586b4.png)

**Comment by rubcap** [comment]
Op de werkgroep-Gebouwenregister van 12 juni was er weinig animo voor dit voorstel.
Als tegenargumenten werden aangehaald:
- Sommige codes uit de generieke codelijst, zoals 'ingemeten' of 'ingemetenGRB', zijn niet toepasbaar op adressen. Je zou al meteen een restrictie op het gebruik van de codelijst voor adresposities moeten zetten.
- Een 'ingeschetst' gebouw zegt nog altijd meer dan een gebouw 'aangeduid door beheerder'. Een positie duid je aan, een polygoon schets je.

**Comment by jensscheerlinck** [comment]
This issue was moved to Informatievlaanderen/OSLO-Discussion#160
