### ISSUE TITLE
Vraag rond 'Adresvoorstelling.locatieaanduiding'

### ISSUE THREAD

**Issue by rubcap** [Informatievlaanderen/Data.Vlaanderen.be#119]
**Context:**
'Locatieaanduiding' komt als attribuut voor in het vocabularium Adres binnen het datatype 'Adresvoorstelling', en eveneens in het vocabularium Gebouw binnen het object 'Gebouweenheid'.

**Vraag:**
Moet 'locatieaanduiding' onder datatype 'Adresvoorstelling' niet van het datatype 'Locatieaanduiding' zijn en multipliciteit [0..*] hebben, om bv. de vleugel, trap, verdieping en deur van een gebouweenheid apart te kunnen opgeven? En is dan geen constraint nodig die ervoor zorgt dat je bv. 'deur' maar één keer kunt opgeven en niet meerdere keren?

**Comment by bertvannuffelen** [comment]
Ruben,

We moeten hier onderscheid maken tussen een data-uitwisselings afspraken en zulke detail constraints over een specifieke stroom van data. Ik pleit ervoor om afspraken zoals "slechts 1 keer een deur" niet op te nemen in het vocabularium/applicatieprofiel als de struktuur van het vocabularium dit niet toelaat om te specifiëren. 

Adresvoorstelling is een vlakke voorstelling van een adres. Als we daarin constraints willen gaan uitdrukken dan moeten we de vlakke struktuur aanpassen. En dat willen we denk ik niet. 

Trouwens als de feed komt van een adresregister dan kunnen we verwachten dat dit slechts 1 keer zal aanwezig zijn omwille van connectie met het gestructureerde Belgische adres.

**Comment by jensscheerlinck** [comment]
This issue was moved to Informatievlaanderen/OSLO-Discussion#159
