### ISSUE TITLE
Toelichting toevoegen aan definitie 'Gebouw.bouwjaar'

### ISSUE THREAD

**Issue by rubcap** [Informatievlaanderen/Data.Vlaanderen.be#121]
**Voorstel:**
In de [kolom 'Gebruik' naast de eigenschap 'bouwjaar'](https://data.vlaanderen.be/doc/applicatieprofiel/gebouw#Gebouw) volgende toelichting toevoegen:
_Verbouwingen en renovaties na de originele oplevering niet meegerekend._

**Motivatie:**
Vermijden dat men dit veld ook gaat gebruiken om een renovatiedatum mee te geven. Definitie scherpstellen.

**Comment by jensscheerlinck** [comment]
This issue was moved to Informatievlaanderen/OSLO-Discussion#157
