### ISSUE TITLE
Splits attribuut 'Gebouw.aantalVerdiepingen' op in bovengronds/ondergronds

### ISSUE THREAD

**Issue by rubcap** [Informatievlaanderen/Data.Vlaanderen.be#122]
**Context:**
Definitie 'aantalVerdiepingen': _Totaal van het aantal boven- en ondergrondse gebouwlagen, bekeken over alle gebouwdelen heen._

**Voorstel:**
Opsplitsen in 'aantalVerdiepingenBovengronds' en 'aantalVerdiepingenOndergronds'.

**Motivatie:**
Een gebruiker die de documentatie niet gelezen heeft, zou 'aantalVerdiepingen' kunnen interpreteren als het aantal bovengrondse verdiepingen. Ook voor hulpdiensten is het relevant het onderscheid te kennen. Wie enkel het bovengronds aantal gebouwlagen kent, kan dit attribuut dan toch invullen en 'aantalVerdiepingenOndergronds' leeg laten. INSPIRE splitst dit ook op.

**Comment by jensscheerlinck** [comment]
This issue was moved to Informatievlaanderen/OSLO-Discussion#156
