### ISSUE TITLE
Typo voor gebruiksnotitie Nationaliteit in Persoon AP

### ISSUE THREAD

**Issue by jensscheerlinck** [Informatievlaanderen/Data.Vlaanderen.be#133]
**Link waar het probleem zich voor doet:** https://data.vlaanderen.be/doc/applicatieprofiel/persoon#Nationaliteit

**Omschrijving van het probleem:** 
Typo in de gebruiksnotitie:

> Nationaliteit wordt doorgaans **autamatisch** verkregen door geboorte

**Omschrijving van een mogelijke oplossing:**

> Nationaliteit wordt doorgaans **automatisch** verkregen door geboorte

**Comment by mvanbrab** [comment]
Opgelost in EA-repository.
