### ISSUE TITLE
Typo voor gebruiksnotitie "Gezin" in Persoon Basis AP

### ISSUE THREAD

**Issue by jensscheerlinck** [Informatievlaanderen/Data.Vlaanderen.be#134]
**Link waar het probleem zich voor doet:** https://data.vlaanderen.be/doc/applicatieprofiel/persoon#Gezin

**Omschrijving van het probleem:** 
> bv een **enpersoonsgezin** of living apart together. Gezinsleden hebben doorgaans dezelfde **Verblijfplaats**.

**Omschrijving van een mogelijke oplossing:**
> bv een **eenpersoonsgezin** of living apart together. Gezinsleden hebben doorgaans dezelfde **verblijfplaats**.

**Comment by mvanbrab** [comment]
Opgelost in EA-repository.
