### ISSUE TITLE
Gegenereerde JSON-LD Context files komen niet in /context terecht

### ISSUE THREAD

**Issue by jensscheerlinck** [Informatievlaanderen/Data.Vlaanderen.be#143]
Gegenereerde JSON-LD Context files komen niet in /context terecht maar  in /doc/applicatieprofiel/*.jsonld

**Comment by wdullaer** [comment]
De json-ld files staan zowel in /context als /doc/applicatieprofiel met een *.json-ld extensie.
Dit kan je gemakkelijk controleren door even in de Oslo-generated repository te kijken
