### ISSUE TITLE
[dienst-transactiemodel] Dode link - uri voor 'behoort tot agent'

### ISSUE THREAD

**Issue by mvanbrab** [Informatievlaanderen/Data.Vlaanderen.be#166]
**Link waar het probleem zich voor doet:** https://test.data.vlaanderen.be/doc/applicatieprofiel/dienst-transactiemodel

**Omschrijving van het probleem:** 'behoort tot agent' verwijst naar http://data.europa.eu/m8g/belongsToAgent, waar verdere doorverwijzing faalt.

**Omschrijving van een mogelijke oplossing:**

**Comment by jensscheerlinck** [comment]
ISA links resolven nu naar het generieke adres: http://52.50.205.146:8890/voc/
Dus voorlopig OK. 

Gesprekken lopende met Europese Commissie om hun dereferencing te verbeteren.
