### ISSUE TITLE
Typo is lidmaatschap bij

### ISSUE THREAD

**Issue by brechtvdv** [Informatievlaanderen/Data.Vlaanderen.be#171]
Is lidmaatschap bij van de klasse Lidmaatschap is gemapt op 'http://www.w3.org/ns/org#Organization' ipv 'http://www.w3.org/ns/org#organization'.

Oplossing: 'target-uri' in het EA model aanpassen

**Comment by mvanbrab** [comment]
Was enkel zo in mandatendatabank. Is in orde. Wordt gesloten met project Publicatie September 2018
