### ISSUE TITLE
Broken link applicatieprofiel gebouwenregister

### ISSUE THREAD

**Issue by michieldk** [Informatievlaanderen/Data.Vlaanderen.be#175]
_Issues in deze repository dienen om technische (broken links, verkeerde mapping van termen op URI's...) of editoriale (typo's, fouten in de HTML weergave...) problemen aan te kaarten. Voor inhoudelijke en semantische issues verwijzen we naar de [OSLO-Discussion repository](https://github.com/Informatievlaanderen/OSLO-Discussion/issues)._

**Link waar het probleem zich voor doet:** https://data.vlaanderen.be/
https://data.vlaanderen.be/doc/applicatieprofiel/gebouwenregister/

**Omschrijving van het probleem:** 
Link is broken: "404 Not Found"

**Omschrijving van een mogelijke oplossing:**

**Comment by bertvannuffelen** [comment]
De laatste versie staat momenteel nog hier: https://test.data.vlaanderen.be/doc/applicatieprofiel/gebouwenregister/
We publiceren dit eerdaags ook op productie.

mvg,

Bert

**Comment by jensscheerlinck** [comment]
Fixed in f79be3291c35e4d46f6941a0f803f057b0a8651a
