### ISSUE TITLE
header/footer referentie aanpassen

### ISSUE THREAD

**Issue by bertvannuffelen** [Informatievlaanderen/Data.Vlaanderen.be#182]
**Link waar het probleem zich voor doet:** https://test.data.vlaanderen.be/standaarden

**Omschrijving van het probleem:** 
header en footer moet verwijzen naar de data.vlaanderen.be en niet vlaanderen.be

**Omschrijving van een mogelijke oplossing:**
aanpassen hash-code

**Comment by KevinHaleydt** [comment]
Headers waren reeds aangepast. Footers zijn nu eveneens in orde

K.
