### ISSUE TITLE
Verantwoordelijke organisatie aanpassen

### ISSUE THREAD

**Issue by wimwo** [Informatievlaanderen/Data.Vlaanderen.be#183]
**Link waar het probleem zich voor doet:** https://test.data.vlaanderen.be/standaarden

**Omschrijving van het probleem:** De verantwoordelijke organisatie van 'Applicatieprofiel Dienst Transactiemodel' linkt naar 'Agentschap Binnenlands Bestuur' (http://data.vlaanderen.be/id/organisatie/OVO001835) terwijl de tekst 'Agentschap Informatie Vlaanderen' is.

**Omschrijving van een mogelijke oplossing:** Ofwel de link aanpassen naar https://data.vlaanderen.be/doc/organisatie/OVO002949 (Agentschap Informatie Vlaanderen) ofwel de tekst aanpassen naar 'Agentschap Binnenlands Bestuur'

**Comment by KevinHaleydt** [comment]
Fixed op hoofdpagina standaardenregister + dcat-ap pagina

**Comment by KevinHaleydt** [comment]
- Rechtzetting van verkeerde aanpassing aan dcat-ap
- Aanpassing juiste Verantwordelijke organisatie voor Dienst Transactiemodel in Standaardenregister

Thanks @bertvannuffelen om dit op te merken

Kevin
