### ISSUE TITLE
Link naar Webcast OSLO-Dienst 2018-05-09-Presentatie not working

### ISSUE THREAD

**Issue by WillemGu** [Informatievlaanderen/Data.Vlaanderen.be#184]
**Link waar het probleem zich voor doet:**

https://test.data.vlaanderen.be/standaarden/erkende-standaarden/vocabularium-dienst/vocabularium-dienst.html
--

**Omschrijving van het probleem:** 
Link naar Webcast OSLO-Dienst 2018-05-09-Presentatie not working

**Comment by KevinHaleydt** [comment]
Fixed issue voor Voc Dienst & AP Diestencataloog
