### ISSUE TITLE
Webcast Link not working: Webcast OSLO-Dienst 2018-05-09 - Presentatie

### ISSUE THREAD

**Issue by WillemGu** [Informatievlaanderen/Data.Vlaanderen.be#185]
**Link waar het probleem zich voor doet:** 

https://test.data.vlaanderen.be/standaarden/kandidaat-standaarden/applicatieprofiel-dienstencataloog/applicatieprofiel-dienstencataloog.html
--

**Omschrijving van het probleem:** 
Webcast Link not working: Webcast OSLO-Dienst 2018-05-09 - Presentatie
--

**Omschrijving van een mogelijke oplossing:**

**Comment by KevinHaleydt** [comment]
Updated link
