### ISSUE TITLE
No read access to documents on google drive

### ISSUE THREAD

**Issue by WillemGu** [Informatievlaanderen/Data.Vlaanderen.be#187]
**Link waar het probleem zich voor doet:**

https://drive.google.com/open?id=1pGJBagybm8IdjvjIDJomeMLYo7wdunv8
https://drive.google.com/open?id=1mUcQ8eGvOe7xOcPcgL80GyRXXeGoSFnO
https://drive.google.com/open?id=1vDc41HfnogxMMSMISLo0bPJRAVRLM98d
https://drive.google.com/open?id=1RsgfcNOAf0sn6CBzLJVSkjZe8GMcGIdj
https://drive.google.com/open?id=1EIWkkqXhsFaYvEtoLOlqGchxJiG-v5wI
https://drive.google.com/open?id=167BsYKO9BrceP4w3G72FjJUwgKN6dIjD
https://drive.google.com/open?id=1dhG6Prx2LxT6FRt731NyTS5ZFfXvAzu9
https://drive.google.com/open?id=1THXhT__xnIWoAnqEn41jenBeWSclcSmR
https://drive.google.com/open?id=15HEyCgCrXeIKO2PyQdCPFrtIk063G_uB
https://drive.google.com/open?id=12q0078L9myM2Fs831fyDOIwxdC9d4tFo
https://drive.google.com/open?id=1V1tGthFvxsFo41tfQ5NZAiyrF62jt8bu
https://drive.google.com/open?id=1PoSisfh9ihJrDt4AzNFW9C67kGoLxu5J
https://drive.google.com/open?id=1Bl2phHC-h49MtEtT-Ea7l8s4FXTDH1bl
https://drive.google.com/open?id=1RXDLzU7_ez9O-xV126P_OfDMqILJyPjL
https://drive.google.com/open?id=1CpdVeg4evqFXiSR8XzFrUimheIfMOFSr
https://drive.google.com/open?id=1sTxswmWW75ha9dPqpL-Q0xIqOrqxnNzQ
https://drive.google.com/open?id=12XtW17VmGGFBVUdyAowwECIM6ozORmoi
https://drive.google.com/open?id=1Kbs_PxEK6Sjx6Ux8qrQTVv-Vu3rWKrgM
https://drive.google.com/open?id=1hBSOTKHEpRmb6_2QxaYHv5Ww5UVG-Rhv
https://drive.google.com/open?id=1FA7WWZnP_xNqtgxkkLgcWpm6bchs7fov
https://drive.google.com/open?id=18tjsyVUE5-nz2V1b6rel-rHjSBHeoILX

**Omschrijving van het probleem:** 
No read access to the following documents (These are links that should be publicly available)

**Omschrijving van een mogelijke oplossing:**

**Comment by KevinHaleydt** [comment]
Links mentioned are updated.
General check needed for other links
