### ISSUE TITLE
Spurios character in the person shape

### ISSUE THREAD

**Issue by EmidioStani** [Informatievlaanderen/Data.Vlaanderen.be#188]
_Issues in deze repository dienen om technische (broken links, verkeerde mapping van termen op URI's...) of editoriale (typo's, fouten in de HTML weergave...) problemen aan te kaarten. Voor inhoudelijke en semantische issues verwijzen we naar de [OSLO-Discussion repository](https://github.com/Informatievlaanderen/OSLO-Discussion/issues)._

**Link waar het probleem zich voor doet:** https://data.vlaanderen.be/

**Omschrijving van het probleem:** 

There is a spurios character in the person shape:

Informatie zoals email, telefoon die toelaat de Persoon te contacteren

In the class ContactPoint

**Omschrijving van een mogelijke oplossing:**

**Comment by jensscheerlinck** [comment]
Probleem dit zich ook voor in het applicatieprofiel:
https://data.vlaanderen.be/doc/applicatieprofiel/persoon-basis/#Persoon%3Acontactinfo

Het gaat op een speciaal karakter in de ap-definition-nl tag.

**Comment by mvanbrab** [comment]
Gecorrigeerd in centrale EA-repo; klaar tegen volgende publicatie.

**Comment by bertvannuffelen** [comment]
@mvanbrab is dit nu opgelost op productie? Indien zo, mag je dit sluiten.

**Comment by mvanbrab** [comment]
@bertvannuffelen: is inderdaad al doorgesijpeld tot productie - ik sluit.
