### ISSUE TITLE
Standaardenregister: kolom publicatiedatum

### ISSUE THREAD

**Issue by GeertThijs** [Informatievlaanderen/Data.Vlaanderen.be#204]
**Link waar het probleem zich voor doet:** https://data.vlaanderen.be/standaarden/.

**Omschrijving van het probleem:** Ook kandidaat-standaarden en standaarden in ontwikkeling hebben een publicatiedatum maar deze kolom ontbreekt momenteel.

**Omschrijving van een mogelijke oplossing:** Kolom toevoegen;

**Comment by bertvannuffelen** [comment]
verbeterde versie is al duidelijker.
