### ISSUE TITLE
Dode links op https://data.vlaanderen.be/standaarden/

### ISSUE THREAD

**Issue by GeertThijs** [Informatievlaanderen/Data.Vlaanderen.be#236]
**Link waar het probleem zich voor doet:** https://data.vlaanderen.be/

- https://data.vlaanderen.be/standaarden/kandidaat-standaarden/applicatieprofiel-adresregister/adresregister.html
- https://data.vlaanderen.be/standaarden/kandidaat-standaarden/vocabularium-transactie/vocabularium-transactie.html
- https://data.vlaanderen.be/standaarden/kandidaat-standaarden/applicatieprofiel-organisatie-basis/

**Omschrijving van het probleem:**
Dode links.

**Omschrijving van een mogelijke oplossing:**
Levende links.

**Comment by KevinHaleydt** [comment]
Hi @GeertThijs ,

https://data.vlaanderen.be/standaarden/kandidaat-standaarden/applicatieprofiel-adresregister/adresregister.html
-> moet aangepast worden naar **applicatieprofiel-**adresregister.html

https://data.vlaanderen.be/standaarden/kandidaat-standaarden/vocabularium-transactie/vocabularium-transactie.html
-> ik ga na of dit een kandidaat of erkende standaard is. index geeft aan dat dit kandidaatstandaard is maar zit onder erkende standaard in de files

https://data.vlaanderen.be/standaarden/kandidaat-standaarden/applicatieprofiel-organisatie-basis/
-> naamgeving moet aangepast worden in files + link moet vervolledigd worden


EDIT:
ik zie net dat Bert enkele van deze links heeft opgelost. Ik controleer morgen of dit allemaal in orde is

**Comment by KevinHaleydt** [comment]
Applicatieprofiel Adresregister & Vocabularium transactie zijn opgelost. 

Applicatieprofiel Organisatie basis moet in directory aangepast worden naar kandidaatstandaard. Files staan momenteel in de erkende standaarden folder.

**Comment by GeertThijs** [comment]
Momenteel volgende dode/foute links in het Standaardenregister:

- https://data.vlaanderen.be/doc/applicatieprofiel/applicatieprofiel-infrastructuurelementen/
- https://data.vlaanderen.be/doc/applicatieprofiel/applicatieprofiel-vegetatie-elementen/
- https://data.vlaanderen.be/doc/applicatieprofiel/applicatieprofiel-terreindeel/
- https://data.vlaanderen.be/doc/applicatieprofiel/applicatieprofiel-begroeid-voorkomen/
- https://data.vlaanderen.be/doc/applicatieprofiel/applicatieprofiel-onbegroeid-voorkomen/
- https://data.vlaanderen.be/doc/applicatieprofiel/applicatieprofiel-waterdeel/
- https://data.vlaanderen.be/doc/applicatieprofiel/applicatieprofiel-watervoorkomen/
- https://data.vlaanderen.be/doc/applicatieprofiel/begraafplaatsenbeheer (link naar contextfile ipv html)
- https://data.vlaanderen.be/doc/applicatieprofiel/besluit-publicatie (link naar contextfile ipv html)
- https://data.vlaanderen.be/doc/applicatieprofiel/mandatendatabank (link naar contextfile ipv html)
- https://data.vlaanderen.be/doc/applicatieprofiel/issue-tracking-voor-burgers-en-organisaties (link naar contextfile ipv html)
- https://data.vlaanderen.be/doc/applicatieprofiel/generieke-terugmeldfaciliteit (link naar contextfile ipv html)
- https://data.vlaanderen.be/doc/applicatieprofiel/contactvoorkeuren (link naar contextfile ipv html)
- https://data.vlaanderen.be/doc/applicatieprofiel/notificatie-basis (link naar contextfile ipv html)
- https://data.vlaanderen.be/doc/applicatieprofiel/dienst-transactiemodel (link naar contextfile ipv html)
- https://data.vlaanderen.be/doc/applicatieprofiel/persoon
- https://data.vlaanderen.be/doc/applicatieprofiel/dienstencataloog (link naar contextfile ipv html)
- https://data.vlaanderen.be/doc/applicatieprofiel/adresregister (link naar contextfile ipv html)
- https://data.vlaanderen.be/standaarden/kandidaat-standaarden/applicatieprofiel-organisatie-basis/index.html (link in het register zelf is dood)
- https://data.vlaanderen.be/doc/applicatieprofiel/wegenregister (link naar contextfile ipv html)
- https://data.vlaanderen.be/standaarden/kandidaat-standaarden/vocabularium-besluiten-mobiliteit/vocabularium-besluiten-mobiliteit.html (geen link naar spec)
- https://data.vlaanderen.be/standaarden/kandidaat-standaarden/applicatieprofiel-besluit-subsidie/applicatieprofiel-besluit-subsidie.html (geen link naar spec)
- https://data.vlaanderen.be/standaarden/kandidaat-standaarden/vocabularium-subsidie/vocabularium-subsidie.html (geen link naar spec)
- https://data.vlaanderen.be/standaarden/standaarden-in-ontwikkeling/vocabularium-mobiliteit/vocabularium-mobiliteit.html (geen link naar spec)
- https://data.vlaanderen.be/standaarden/standaarden-in-ontwikkeling/applicatieprofiel-mobiliteit/applicatieprofiel-mobiliteit.html (geen link naar spec)
- https://data.vlaanderen.be/standaarden/standaarden-in-ontwikkeling/besluitvorming/besluitvorming.html (geen link naar spec)
- https://data.vlaanderen.be/standaarden/standaarden-in-ontwikkeling/cultureel-erfgoed/cultureel-erfgoed.html (geen link naar spec)

**Comment by mvanbrab** [comment]
Voortgaande op vorige commentaar: de naam voor volgende entries zou moeten aangepast worden in lijn met de aanpassing van de naam van het vocabularium en het applicatieprofiel ("Mobiliteit: Trips & Aanbod")
https://data.vlaanderen.be/standaarden/standaarden-in-ontwikkeling/vocabularium-mobiliteit/vocabularium-mobiliteit.html
https://data.vlaanderen.be/standaarden/standaarden-in-ontwikkeling/applicatieprofiel-mobiliteit/applicatieprofiel-mobiliteit.html

**Comment by GeertThijs** [comment]
> Momenteel volgende dode/foute links in het Standaardenregister:
> 
> * https://data.vlaanderen.be/doc/applicatieprofiel/applicatieprofiel-infrastructuurelementen/
> * https://data.vlaanderen.be/doc/applicatieprofiel/applicatieprofiel-vegetatie-elementen/
> * https://data.vlaanderen.be/doc/applicatieprofiel/applicatieprofiel-terreindeel/
> * https://data.vlaanderen.be/doc/applicatieprofiel/applicatieprofiel-begroeid-voorkomen/
> * https://data.vlaanderen.be/doc/applicatieprofiel/applicatieprofiel-onbegroeid-voorkomen/
> * https://data.vlaanderen.be/doc/applicatieprofiel/applicatieprofiel-waterdeel/
> * https://data.vlaanderen.be/doc/applicatieprofiel/applicatieprofiel-watervoorkomen/
> * https://data.vlaanderen.be/doc/applicatieprofiel/begraafplaatsenbeheer (link naar contextfile ipv html)
> * https://data.vlaanderen.be/doc/applicatieprofiel/besluit-publicatie (link naar contextfile ipv html)
> * https://data.vlaanderen.be/doc/applicatieprofiel/mandatendatabank (link naar contextfile ipv html)
> * https://data.vlaanderen.be/doc/applicatieprofiel/issue-tracking-voor-burgers-en-organisaties (link naar contextfile ipv html)
> * https://data.vlaanderen.be/doc/applicatieprofiel/generieke-terugmeldfaciliteit (link naar contextfile ipv html)
> * https://data.vlaanderen.be/doc/applicatieprofiel/contactvoorkeuren (link naar contextfile ipv html)
> * https://data.vlaanderen.be/doc/applicatieprofiel/notificatie-basis (link naar contextfile ipv html)
> * https://data.vlaanderen.be/doc/applicatieprofiel/dienst-transactiemodel (link naar contextfile ipv html)
> * https://data.vlaanderen.be/doc/applicatieprofiel/persoon
> * https://data.vlaanderen.be/doc/applicatieprofiel/dienstencataloog (link naar contextfile ipv html)
> * https://data.vlaanderen.be/doc/applicatieprofiel/adresregister (link naar contextfile ipv html)
> * https://data.vlaanderen.be/standaarden/kandidaat-standaarden/applicatieprofiel-organisatie-basis/index.html (link in het register zelf is dood)
> * https://data.vlaanderen.be/doc/applicatieprofiel/wegenregister (link naar contextfile ipv html)
> * https://data.vlaanderen.be/standaarden/kandidaat-standaarden/vocabularium-besluiten-mobiliteit/vocabularium-besluiten-mobiliteit.html (geen link naar spec)
> * https://data.vlaanderen.be/standaarden/kandidaat-standaarden/applicatieprofiel-besluit-subsidie/applicatieprofiel-besluit-subsidie.html (geen link naar spec)
> * https://data.vlaanderen.be/standaarden/kandidaat-standaarden/vocabularium-subsidie/vocabularium-subsidie.html (geen link naar spec)
> * https://data.vlaanderen.be/standaarden/standaarden-in-ontwikkeling/vocabularium-mobiliteit/vocabularium-mobiliteit.html (geen link naar spec)
> * https://data.vlaanderen.be/standaarden/standaarden-in-ontwikkeling/applicatieprofiel-mobiliteit/applicatieprofiel-mobiliteit.html (geen link naar spec)
> * https://data.vlaanderen.be/standaarden/standaarden-in-ontwikkeling/besluitvorming/besluitvorming.html (geen link naar spec)
> * https://data.vlaanderen.be/standaarden/standaarden-in-ontwikkeling/cultureel-erfgoed/cultureel-erfgoed.html (geen link naar spec)

Verbeterd, met uitzondering van de gevallen waar (nog) geen link in het Standaardenregister voorkomt. We gaan er voorlopig van uit dat dit een bewuste keuze vd thema-captain is.

**Comment by GeertThijs** [comment]
> Voortgaande op vorige commentaar: de naam voor volgende entries zou moeten aangepast worden in lijn met de aanpassing van de naam van het vocabularium en het applicatieprofiel ("Mobiliteit: Trips & Aanbod")
> https://data.vlaanderen.be/standaarden/standaarden-in-ontwikkeling/vocabularium-mobiliteit/vocabularium-mobiliteit.html
> https://data.vlaanderen.be/standaarden/standaarden-in-ontwikkeling/applicatieprofiel-mobiliteit/applicatieprofiel-mobiliteit.html

Zou in orde moeten zijn...

**Comment by mvanbrab** [comment]
De pagina's hebben nu al een nieuwe URL; nu nog de **titels** op die pagina's...
https://data.vlaanderen.be/standaarden/standaarden-in-ontwikkeling/vocabularium-mobiliteit-trips-en-aanbod/index.html
https://data.vlaanderen.be/standaarden/standaarden-in-ontwikkeling/applicatieprofiel-mobiliteit-trips-en-aanbod/index.html

**Comment by GeertThijs** [comment]
> De pagina's hebben nu al een nieuwe URL; nu nog de **titels** op die pagina's...
> https://data.vlaanderen.be/standaarden/standaarden-in-ontwikkeling/vocabularium-mobiliteit-trips-en-aanbod/index.html
> https://data.vlaanderen.be/standaarden/standaarden-in-ontwikkeling/applicatieprofiel-mobiliteit-trips-en-aanbod/index.html

Zou in orde moeten zijn.

**Comment by GeertThijs** [comment]
> Applicatieprofiel Adresregister & Vocabularium transactie zijn opgelost.
> 
> Applicatieprofiel Organisatie basis moet in directory aangepast worden naar kandidaatstandaard. Files staan momenteel in de erkende standaarden folder.

Done.

**Comment by GeertThijs** [comment]
> **Link waar het probleem zich voor doet:** https://data.vlaanderen.be/
> 
> * https://data.vlaanderen.be/standaarden/kandidaat-standaarden/applicatieprofiel-adresregister/adresregister.html
> * https://data.vlaanderen.be/standaarden/kandidaat-standaarden/vocabularium-transactie/vocabularium-transactie.html
> * https://data.vlaanderen.be/standaarden/kandidaat-standaarden/applicatieprofiel-organisatie-basis/
> 
> **Omschrijving van het probleem:**
> Dode links.
> 
> **Omschrijving van een mogelijke oplossing:**
> Levende links.

Ook deze zijn nu in orde.

**Comment by GeertThijs** [comment]
Opgelost, met uitzondering van de ontbrekende specs. Zie daar voor issue https://github.com/Informatievlaanderen/OSLO-Standaarden/issues/66.
