### ISSUE TITLE
Voorstel nieuwe definitie (vertaling) Formeel Kader (Formal Framework)

### ISSUE THREAD

**Issue by laurensdv** [Informatievlaanderen/Data.Vlaanderen.be#24]
> Het geheel van regelgeving, rechtshandelingen en beleidskeuzes waarop een bestuurshandeling gebaseerd is.

**Comment by jensscheerlinck** [comment]
This issue was moved to Informatievlaanderen/OSLO-Discussion#181

**Comment by GeertThijs** [comment]
Oorspronkelijke definitie in CPSVAP 2.0:

> This class represents the legislation, policy or policies that lie behind the Rules that govern the service. The definition and properties of the Formal Framework class in the CPSV-AP are aligned with the ontology included in “Council conclusions inviting the introduction of the European Legislation Identifier (ELI)

Huidige definitie in CPSVAP 2.2:

> This class represents the legislation, policy or policies that lie behind the Rules that govern the service. The definition and properties of the Legal Resource class in the CPSV-AP are aligned with the ontology included in “Council conclusions inviting the introduction of the European Legislation Identifier (ELI)”. For describing the attributes of a Legal Resource (labels, preferred labels, alternative labels, definition …) we refer to the ELI ontology.

Huidige AP-definitie in OSLO:
> Geheel van formele documenten dat regels, rechten, plichten ten aanzien van burgers, overheden, bedrijven etc beschrijft. 

Voorstel van Laurens voor vertaling definitie uit CPSVAP:

> Het geheel van regelgeving, rechtshandelingen en beleidskeuzes waarop een bestuurshandeling gebaseerd is.

Hierover dit:

- Niet duidelijk of Laurens het zowel over de VOC als AP definitie heeft.
- Bestuurshandeling: doet vermoeden dat deze vraag tot herdefinitie te maken heeft met OSLO-Bestuur?
- In CPSVAP wordt FormalFramework hernoemd naar LegalResource welke in Bestuur op zijn beurt Rechtsgrond is geworden.

AP-definitie van Rechtsgrond:
> Een legaal concept dat los staat van een bepaalde vorm (het achterliggende idee).

Definitie van LegalResource:
> A distinct intellectual creation (i.e., the intellectual content).

Hoe koppelen we dit allemaal aan elkaar?

**Comment by jensscheerlinck** [comment]
This issue was moved to Informatievlaanderen/OSLO-Discussion#181
