### ISSUE TITLE
Uri voldoet niet aan de uri-standaard van de vlaamse overheid.

### ISSUE THREAD

**Issue by gezever** [Informatievlaanderen/Data.Vlaanderen.be#244]
**Link waar het probleem zich voor doet:** https://data.vlaanderen.be/
https://data.vlaanderen.be/doc/organisatie/OVO003323.ttl

**Omschrijving van het probleem:** 
<https://data.vlaanderen.be/.well-known/genid/hoedanigheid-034d0af7-8bf1-e555-a0aa-d460dea36339> a dc:Agent,
    <https://data.vlaanderen.be/ns/organisatie#Hoedanigheid>
De uri https://data.vlaanderen.be/.well-known/genid/hoedanigheid-034d0af7-8bf1-e555-a0aa-d460dea36339 is niet conform de uri-standaard.

**Omschrijving van een mogelijke oplossing:**
Een correct formaat is:
 https://data.vlaanderen.be/id/hoedanigheid/034d0af7-8bf1-e555-a0aa-d460dea36339
of
 https://data.vlaanderen.be/id/agent/034d0af7-8bf1-e555-a0aa-d460dea36339
of
 https://data.organisatie.vlaanderen.be/id/hoedanigheid/034d0af7-8bf1-e555-a0aa-d460dea36339
of
 https://data.organisatie.vlaanderen.be/id/agent/034d0af7-8bf1-e555-a0aa-d460dea36339

**Comment by bertvannuffelen** [comment]
Dag Geert,

inderdaad, maar dit is een speciale. 
Het is een skolem volgens de definitie van RDF (https://www.w3.org/TR/rdf11-concepts/ sectie 3.5).

M.a.w. je moet dit interpreteren als een blank node.

mvg,

Bert

**Comment by gezever** [comment]
Dag Bert,
Bedankt voor de informatie, dit is nieuw voor mij.
Groeten,
Geert

**Comment by bertvannuffelen** [comment]
Ik ga akkoord dat is niet het meest gekende 'feature' van RDF. Maar het lost wel op een elegante wijze de uitdaging op om op een onafhankelijke manier informatie over een blank node aan te maken (door 2 parallele processen). 

De doelstelling was ook om op data.vlaanderen.be enkel voor de Persistente Identificatoren een URI volgens de URI richtlijnen te hebben en voor alle andere een blank node. 
Met deze feature lukt dat. 

Waar procesmatig mogelijk zullen we een "klassieke" blank node gebruiken. Wat iets meer met de verwachtingen overeekomt.

mvg,

Bert
