### ISSUE TITLE
Verplicht "wordtBeschrevenDoor" meegeven voor Object

### ISSUE THREAD

**Issue by jensscheerlinck** [Informatievlaanderen/Data.Vlaanderen.be#31]
Klasse Object heeft momenteel in het Generiek AP een verplichte eigenschap "wordtBeschrevenDoor".

Geldt dit bijgevolg ook voor de subklassen van Object, bv. Persoon en Organisatie?

**Comment by DieterDePaepe** [comment]
Zo lijkt het inderdaad wel, maar dat kan volgens mij niet bedoeld zijn.
Best eens met @GeertThijs checken...

**Comment by GeertThijs** [comment]
Deze relatie is intussen van richting veranderd. Heet nu isTijdspecialisatieVan en Record werd Versie. Cardinaliteit werd en passant ook aangepast, is niet langer verplicht wat bovengenoemd probleem oplost.
