### ISSUE TITLE
org:organization komt niet voor in Organisatie AP

### ISSUE THREAD

**Issue by DieterDePaepe** [Informatievlaanderen/Data.Vlaanderen.be#34]
Wellicht door conflict van naam: zie #23

**Comment by GeertThijs** [comment]
Wat te verstaan onder "komt niet voor". Staat in diagram, staat in spec...

**Comment by jensscheerlinck** [comment]
Is opgenomen in het vocabularium met de vertaling "is lidmaatschap bij":

Zie: https://data.vlaanderen.be/ns/organisatie
