### ISSUE TITLE
Ongeldige JSON-LD context voor Besluitvorming AP

### ISSUE THREAD

**Issue by erikap** [Informatievlaanderen/Data.Vlaanderen.be#343]
**Link waar het probleem zich voor doet:** 
 https://data.vlaanderen.be/doc/applicatieprofiel/besluitvorming/kandidaatstandaard/2020-10-01/context/besluitvorming-ap.jsonld

**Omschrijving van het probleem:** 
Ongeldige JSON-LD context

**Omschrijving van een mogelijke oplossing:**
De JSON-LD context bevat een lege string als `@type` voor `Stuk.taal`

```
"Stuk.taal": {
    "@id": "http://purl.org/dc/terms/language",
    "@type": ""
}
```

Dit moet zijn:
```
"Stuk.taal": {
    "@id": "http://purl.org/dc/terms/language",
    "@type": "@id"
}
```

**Comment by bertvannuffelen** [comment]
@erikap, bedankt om het te melden.

Het bron van het probleem ligt dat in het model van de besluitvorming voor Stuk.taal geen range is opgenomen. Waarschijnlijk is dat een vergetelheid. Ik signaleer het aan de editors.

**Comment by dimi-schepers** [comment]
Opgelost in erkende versie: https://data.vlaanderen.be/doc/applicatieprofiel/besluitvorming/#jsonld
