### ISSUE TITLE
Persoon: alternatievenaam zou eigen URI moeten krijgen

### ISSUE THREAD

**Issue by DieterDePaepe** [Informatievlaanderen/Data.Vlaanderen.be#36]
De `alternatieveNaam` van een `Persoon` is gemapt op `foaf:name`. Deze wordt echter ook gebruikt als parentURI voor `volledigeNaam`. Hierdoor kan een reasoner geen onderscheid maken tussen een `volledigeNaam` en `alternatieveNaam` indien men waarden van `foaf:name` binnenkrijgt.

**Comment by mvanbrab** [comment]
**Huidige situatie:**

Persoon.volledigeNaam
	- heeft eigen URI (https://data.vlaanderen.be/ns/persoon#volledigeNaam)
	- heeft parentURI tag (http://xmlns.com/foaf/0.1/name)
	- waaruit volgt: https://data.vlaanderen.be/ns/persoon#volledigeNaam rdfs:subPropertyOf http://xmlns.com/foaf/0.1/name

Persoon.alternatieveNaam
	- heeft uri tag (http://xmlns.com/foaf/0.1/name)

In een dataset waarin voorkomt:
	s https://data.vlaanderen.be/ns/persoon#volledigeNaam "David Howell Evans"
is dus ook impliciet aanwezig:
	s http://xmlns.com/foaf/0.1/name "David Howell Evans"
(m.a.w. er is ook een onverwachte waarde voor Persoon.alternatieveNaam, nl. "David Howell Evans")

In een dataset waarin voorkomt:
	s https://data.vlaanderen.be/ns/persoon#volledigeNaam "David Howell Evans"
	s http://xmlns.com/foaf/0.1/name "The Edge"
is dus ook impliciet aanwezig:
	s http://xmlns.com/foaf/0.1/name "David Howell Evans"
(m.a.w. er zijn nu twee verschillende waarden voor Persoon.alternatieveNaam, nl.  de verwachte "The Edge" en de onverwachte "David Howell Evans")

**Voorgestelde verbetering (in overleg met DieterDePaepe):**

Persoon.volledigeNaam
	- heeft eigen URI (https://data.vlaanderen.be/ns/persoon#volledigeNaam)
	- heeft parentURI tag (http://xmlns.com/foaf/0.1/name)
	- waaruit volgt: https://data.vlaanderen.be/ns/persoon#volledigeNaam rdfs:subPropertyOf http://xmlns.com/foaf/0.1/name

Persoon.alternatieveNaam
	- heeft eigen URI (https://data.vlaanderen.be/ns/persoon#alternatieveNaam)
	- heeft parentURI tag (http://xmlns.com/foaf/0.1/name)
	- waaruit volgt: https://data.vlaanderen.be/ns/persoon#alternatieveNaam rdfs:subPropertyOf http://xmlns.com/foaf/0.1/name
	
In een dataset waarin voorkomt:
	s https://data.vlaanderen.be/ns/persoon#volledigeNaam "David Howell Evans"
is dus ook impliciet aanwezig:
	s http://xmlns.com/foaf/0.1/name "David Howell Evans"
(wat geen probleem is; geen onverwachte Persoon.alternatieveNaam)

In een dataset waarin voorkomt:
	s https://data.vlaanderen.be/ns/persoon#volledigeNaam "David Howell Evans"
	s https://data.vlaanderen.be/ns/persoon#alternatieveNaam "The Edge"
is dus ook impliciet aanwezig:
	s http://xmlns.com/foaf/0.1/name "David Howell Evans"
	s http://xmlns.com/foaf/0.1/name "The Edge"
(wat geen probleem is; geen onverwachte tweede waarde voor Persoon.alternatieveNaam)

In een dataset waarin voorkomt:
	s http://xmlns.com/foaf/0.1/name "David Howell Evans"
	s http://xmlns.com/foaf/0.1/name "The Edge"
worden op basis van deze regels geen waarden toegekend aan Persoon.volledigeNaam of Persoon.alternatieveNaam)

**Bedenking:**

Kan aangepast worden, liefst zo snel mogelijk, indien er nog geen datasets in gebruik zijn voor de betreffende applicatieprofielen.

OSLO-Persoon wordt gebruikt in:
	- OSLO-Mandaat (VOC en AP; AP gebruikt enkel betreffende property alternatievePersoon)
	- OSLO-Persoon (VOC en AP; AP gebruikt beide betreffende properties)
	- OSLO-Organisatie (VOC en AP; AP gebruikt betreffende properties niet)
	- OSLO-Generiek (VOC en AP; AP gebruikt betreffende properties niet)

**Comment by bertvannuffelen** [comment]
een klassiek geval van disambiguatie. Lijkt me correct.

**Comment by mvanbrab** [comment]
Gedaan zoals voorgesteld. Beschikbaar in EA repository.
