### ISSUE TITLE
generiek: http://data.europa.eu/eli/ontology#language

### ISSUE THREAD

**Issue by bertvannuffelen** [Informatievlaanderen/Data.Vlaanderen.be#41]
Waarom is voor "taal" in generiek voor deze specifieke URI gekozen?

<http://data.europa.eu/eli/ontology#language>

waarom niet dct:language?

Merk op dat je hierdoor domein en range vastlegt op <http://data.europa.eu/eli/ontology#Language>:

<rdfs:domain rdf:resource="http://data.europa.eu/eli/ontology#LegalExpression"/>
<rdfs:range rdf:resource="http://data.europa.eu/eli/ontology#Language"/>

waarbij de range op zijn beurt weer gedefinieerd is als de concepten uit <http://publications.europa.eu/resource/authority/language>

Dit is een modelingsprincipe dat voor alle eigenschappen die gedefinieerd worden door de Publications Office wordt gebruikt. 
En daar zijn nog andere language properties voor andere domeinen.

Voor generiek is dit dus een sterk beperkende keuze. dcterms is veel vrijer qua domain en range.
Is dit de bedoeling?

**Comment by DieterDePaepe** [comment]
Dag Bert,

we zagen een overlap in semantiek tussen `cpsv:FormalFramework` (FormeelKader) en `eli:LegalExpression`. Gezien ELI al een taal property op LegalExpression had gedefinieerd, hebben we die term overgenomen.

Ik zie geen beperking die `eli:language` heeft tegenover `dcterms:language`.

**Comment by bertvannuffelen** [comment]
Dieter,

wel als je OWL interpretatie doet. Want dan betekent dat elk subject een eli:LegalExpression wordt. 
eli:language a owl:ObjectProperty.
eli:language rdfs:domain eli:LegalExpression.
eli:language rdfs:range eli:Language.

dan volgt voor een specifieke instantie:

werk:123 eli:language mdr:nl.

dat werk:123  een eli:LegalExpression is.

En dat is niet denk ik generiek. Niet elk werk:123 is een eli:LegalExpression. Als generiek property is eli:language niet geschikt.

**Comment by DieterDePaepe** [comment]
De kernvraag is dus of elk `FormeelKader` een `Legale Verschijningsvorm` is. Mijn interpretatie van FormeelKader spreekt dit niet tegen. Maar mogelijks mis ik wat vakkennis hier over expliciete usecases.

**Comment by jensscheerlinck** [comment]
This issue was moved to Informatievlaanderen/OSLO-Discussion#179

**Comment by GeertThijs** [comment]
Blijkbaar is een FormalFramework (FormeelKader) een LegalResource (Rechtsgrond), zie versie 2.2 van CPSVAP. En die heeft geen taal, het is de LegalExpression (LegaleVerschijningsvorm) die de LegalResource realiseert die een taal heeft. Voor meer info over CPSVAP 2.2 tov 2.0: zie https://vlaamseoverheid.atlassian.net/wiki/spaces/OSLO/pages/609157416/Impact+wijzigingen+CPSVAP+2.0+to+2.2. Kortom: vervanging van FormeelKader door Rechtsgrond lost dit probleem op...
