### ISSUE TITLE
Bestuurseenheid vs AdministratieveEenheid

### ISSUE THREAD

**Issue by GeertThijs** [Informatievlaanderen/Data.Vlaanderen.be#42]
Definitie Bestuurseenheid (LBLOD):

- Publieke, bestuurlijke organisatie verbonden aan een territoriaal omschreven gebied met bepaalde verantwoordelijkheden waarbinnen het bestuurshandelingen kan stellen.

Definitie AdministratieveEenheid (INSPIRE):

- Unit of administration where a Member State has and/or exercises jurisdictional rights, for local, regional and national governance.

Een verwant begrip met AdministratieveEenheid is Jurisdictie (OSLO):

- Het gebied waarover de rechtsmacht van een overheid zich uitstrekt.

Verwant ipv gelijk want het bij Jurisdictie zowel om de bevoegdheid gaat om rechtsmacht uit te oefenen, als over het territorium waarbinnen die wordt uitgeoefend, zie volgende definities voor meer info:

- http://www.encyclo.nl/begrip/jurisdictie.

- https://nl.wikipedia.org/wiki/Jurisdictie.

-  A jurisdiction, typically a country, dealing with and making pronouncements on legal matters (recursieve definitie van ISA).

Maar misschien kunnen we het als volgt samenvatten: Een Bestuursheenheid oefent Jurisdictie uit binnen een bepaald AdministratieveEenheid. Dus toch wel aparte begrippen?

**Comment by DieterDePaepe** [comment]
De INSPIRE definitie vind ik dubbelzinnig in de zin dat ik het zowel als iets organisatorisch als iets geografisch kan interpreteren. De LBLOD definitie is duidelijk organisatorisch en de OSLO definitie duidelijk geografisch.

Administratieve eenheid zou ook nog iets kunnen zijn dat een bestuurseenheid heeft.

Hier zou input van Veronique handig kunnen zijn, omdat het ook over legale definities gaat.

**Comment by GeertThijs** [comment]
- Er is volgens mij gewoon geen verschil tussen een Bestuurseenheid en een AdministratieveEenheid. Meer zelfs INSPIRE vertaalt AdministrativeUnit zelf als Bestuurseenheid: zie p28 in https://www.geopunt.be/~/media/geopunt/geowijzer/inspire/documenten/uitvoeringsbepalingdataspecificaties.pdf. En de definities omvatten allebei het bestuurlijke (bij INSPIRE vallen woorden als excercising & governance). Alleen gaat OSLO-Besluit misschien wat ver door een Bestuurseenheid ook op te vatten als een PubliekeOrganisatie. Een Bestuurseenheid is dan ineens ook een groep mensen die als groep kan handelen.

- Jurisdictie (in de betekenis van rechtsgebied) lijkt mij wel te handhaven als apart begrip. Heeft betrekking op bevoegdheid waaronder je valt als je je bv als Persoon op een of ander grondgebied begeeft. Lijkt iets anders dan een territoriale indeling om te besturen of rechtsbevoegdheid om te besturen.

**Comment by GeertThijs** [comment]
Concreet zou dit als volgt vertaald kunnen worden in de UML-modellen:

- We maken een namespace bij die we Bestuurseenheid noemen, we plaatsen daarin Bestuurseenheid.
- De huidige AdministratieveEenheid schrappen we, in OSLO-Adres vervangen we de relatie Gemeentenaam.isAfgeleidVan.AdministratieveEenheid(inDeRolvanGemeente) door Gemeentenaam.isAfgeleidVan.ABestuurseenheid(inDeRolvanGemeente).
- De overerving van PubliekeOrganisatie schrappen we tot nader order.
- Bestuursorgaan verplaatsen we naar de namespace OSLO-Organisatie.

**Comment by GeertThijs** [comment]
Intussen stuit ik op een interessant tegenvoorbeeld, nl het arrondissement. Hiervan wordt eigenlijk beweerd (zie ref https://nl.wikipedia.org/wiki/Gemeente_(bestuur) en ook https://nl.wikipedia.org/wiki/Bestuurlijke_indeling_van_Belgi%C3%AB) dat het een AdminstratieveEenheid maar geen BestuursEenheid is. Maw: niet alle AdministratieveEenheden worden blijkbaar bestuurd. Anderzijds is een district volgens wikipedia een bestuurslaag (zie https://nl.wikipedia.org/wiki/Gemeente_(bestuur)). Tegenstrijdig dan weer is dat districten niet als een administratief niveau worden beschouwd (zie INSPIRE Address spec http://inspire.ec.europa.eu/documents/Data_Specifications/INSPIRE_DataSpecification_AD_v3.0.pdf tabel A p83). Kortom: Bestuurseenheden zijn AdministratieveEenheden die rechtstreeks bestuurd worden. Als dat werkelijk zo is kunnen we de boel laten wat hij is? Wel misschien een namespace AdministratieEnBestuur creëren?

**Comment by DieterDePaepe** [comment]
Katrien had me gevraagd om input op deze issue.

Eerst wat commentaar op Geert:

> Tegenstrijdig dan weer is dat districten niet als een administratief niveau worden beschouwd (zie INSPIRE Address spec http://inspire.ec.europa.eu/documents/Data_Specifications/INSPIRE_DataSpecification_AD_v3.0.pdf tabel A p83).

Volgens mij wel, maar ipv de term "district", gebruikt men "arrondissement". Zie tabel E.3.1.1 van dezelfde pdf.

---

Ik denk dat "Bestuurseenheid" een woord is dat in verschillende contexten een verschillende betekenis meekrijgt. Het is dus moeilijk om een uniek onderscheidend woord te vinden voor alles, daarom gebruiken we URIs. Vanuit mijn standpunt is het ok dat een aantal begrippen in OSLO dezelfde naam draagt, zolang ze een unieke URI hebben en de definitie voor elk het onderscheid maakt.

Dit zijn de concepten die ik herken in deze discussie:

# lblod:Bestuurseenheid
> Publieke, bestuurlijke organisatie verbonden aan een territoriaal omschreven gebied met bepaalde verantwoordelijkheden waarbinnen het bestuurshandelingen kan stellen. ([Bron: OSLO vocs](http://data.vlaanderen.be/ns/besluit#Bestuurseenheid))

 Dit is bedoeld als de organisatie die bestuurt, zoals bvb "Stadbestuur Gent", met dus de nadruk op de (veranderlijke) groep actoren die het bestuurt. Deze kan dan opgedeeld worden in kleinere organen, bvb: burgemeester, college, ... In de definitie liggen 2 nadrukken: 
- publieke organisatie: Het gaat dus om een groep die handelingen kan stellen
- verbonden aan een territoriaal omschreven gebied: Voor welk territorium is het verantwoordelijk (= `Inspire:Bestuurseenheid` volgens mij)

# Inspire:Bestuurseenheid / Inspire:AdministrativeUnit
> Bestuurlijke eenheid waarover een lidstaat rechtsbevoegdheid heeft en/of uitoefent, in het kader van lokaal, regionaal of nationaal bestuur. ([Bron: 4.1.2 p18 vertaling INSPIRE](http://inspire.ec.europa.eu/documents/Data_Specifications/INSPIRE_DataSpecification_AD_v3.0.pdf))

Ik interpreteer dit als het gebied waar een bestuur (`lblod:Bestuurseenheid`) zijn bevoegdheid heeft. Voorbeelden zijn de gewesten, provincies, gemeentes en de arrondissementen.

Als we kijken naar de fragmenten uit wikipedia die Geert linkte:
> De provincies en Brussel zijn verder onderverdeeld 43 bestuurlijke Arrondissementen (arrondissements administratives) als administratieve indeling van de provincies. De arrondissementscommissaris is een ambtenaar; hij "bestuurt" niet. Hij vertegenwoordigt de provinciegouverneur.

> Een Belgisch arrondissement is geen bestuurslaag, maar een administratieve indeling.
De gemeenten zijn administratief opgedeeld in deelgemeenten. Deze afdelingen vormen geen bestuurslaag.

Komt dit volgens mij overeen met het onderscheid `lblod:BestuursEenheid` (= bestuurslaag)  en `Inspire:BestuursEenheid` (= geen bestuurslaag).

Je kan je afvragen of volgende de Inspire definitie elke `Inspire:Bestuurseenheid` moet bedoeld zijn om "direct" bestuurt te worden of niet, maar gezien ze zelf arrondissementen beschouwen als `Inspire:Bestuureenheid` vermoed ik van niet. Uiteindelijk worden ze nog steeds bestuurd via de hogerliggende hiërarchie.

# Jurisdiction
> Jurisdictie is een ander woord voor rechtsmacht en heeft betrekking op het gebied waarover een overheidsorgaan bevoegd is. Zowel de wetgevende, uitvoerende als rechtsprekende machten hebben hun specifieke jurisdictie. In de rechtspraak wordt er ook onderscheid gemaakt tussen rechtsmacht ratione materiae (welk type zaken mag de rechtbank behandelen), ratione personae (over welke personen mag de rechtbank een uitspraak doen) en ratione temporis (mag de rechtbank uitspraak doen over zaken die op die datum zijn gebeurd). In het recht en de rechtspraak wordt rechtsmacht vaak in deze tweede, ratione personae, betekenis gebruikt. (Bron: [wikipedia](https://nl.wikipedia.org/wiki/Jurisdictie))

Ik vind dit nog een vaag begrip, maar `Jurisdictie` lijkt dus meerdere zaken te vatten: "waar/wie/wat". In die zin kan je argumenteren dat `Inspire:Bestuurseenheid` de ruimtelijke specialisatie van een `Jurisdictie` is.

---

Wat kan er dus aangepast worden in OSLO? Op zich lijkt me alles correct zoals het is, maar volgende aanpassingen zijn mogelijk:
- Invoeren van een term voor `Inspire:BestuursEenheid` te dekken. Die zou ik persoonlijk bij Bestuur steken.
- De AdministratieveEenheid uit OSLO:AdresRegister kan door deze nieuwe term vervangen worden.
- De [`besluit:Bestuurseenheid:werkingsgebied`](http://data.vlaanderen.be/doc/applicatieprofiel/besluit-publicatie#Bestuurseenheid%3Awerkingsgebied) kan met de nieuwe term gekoppeld worden.

**Comment by GeertThijs** [comment]
Uiteindelijk hebben we het volgende besloten:

- AdministratieveEenheid blijft bestaan naast Bestuurseenheid
- We erkennen dat beide een verschillende invalshoek hebben: AdministratieveEenheid geografisch, Bestuurseenheid bestuurlijk
- Aan de definities moet niets worden veranderd, Bestturseenheid blijft ook een subklasse van PubliekeOrganisatie
- Behalve dat we Bestuurseenheid in een namespace OSLO-Bestuur plaatsen en AdministratieveEenheid verplaatsen vanOSLO- Placeholder naar OSLO-Geografie
- Verleggen we de koppelingen isGelegenIn en isAfgeleidVan in OSLO-Adres naar AdministratieveEenheid en vervangen we Agent door Bestuurseenheid voor de koppelingen isToegekendDoor
