### ISSUE TITLE
Toepassing van Taalstring

### ISSUE THREAD

**Issue by GeertThijs** [Informatievlaanderen/Data.Vlaanderen.be#45]
LBLOD maakt in vergelijking met de de OSLO basisdomeinen eerder zuinig gebruik vh datatype Taalstring. In OSLO gebruikten we Taalstring voor elke String waarvan de waarde mogelijk in meerdere talen gesteld kan worden, bv voor Organisatie.beschrijving wel maar niet voor Persoon.voornaam. Welke regel volgen we hier?

**Comment by DieterDePaepe** [comment]
De attributen op `Rechtsgrond`, `Legale Verschijningsvorm` zijn attributen overgenomen uit ELI, die ze als `String` definieert (en `LangString` wellicht beter zou zijn).

Enkel `Agendapunt:titel` is te strikt gedefinieerd, dat zou ook een `Literal` of `LangString` kunnen zijn.

De regel is volgens mij: als iets effectief vertaald kan worden en dezelfde betekenis heeft, is het een `LangString` (zoals de beschrijving van een organisatie). Een persoonnaam daarentegen is niet te vertalen, want de persoon heeft maar 1 bepaalde naam (of een beperkt aantal) gekregen. Een persoon die in het Nederlands "Jan" noemt, noemt niet "Jean" in het Frans.

**Comment by GeertThijs** [comment]
Goede regel. TODO: nazien of deze ook in andere vocabularia is gerespecteerd.

**Comment by jensscheerlinck** [comment]
This issue was moved to Informatievlaanderen/OSLO-Discussion#178
