### ISSUE TITLE
Toepassing van GetypeerdeString

### ISSUE THREAD

**Issue by GeertThijs** [Informatievlaanderen/Data.Vlaanderen.be#47]
Bij Verschijningsvorm.inhoud zie ik een GetypeerdeString als datatype. Waarom?

**Comment by DieterDePaepe** [comment]
Men kan argumenteren dat een `LangString` (`TaalString`) ook zou voldoen, maar door het een `Literal` (`GetypeerdeString`) te maken, is het ook mogelijk om HTML op te slaan, wat kan relevant zijn voor markup beter te bewaren.

**Comment by GeertThijs** [comment]
TODO: onderzoeken of er in de andere vocabularia gelijkaardige gevallen zijn.

**Comment by jensscheerlinck** [comment]
This issue was moved to Informatievlaanderen/OSLO-Discussion#177
