### ISSUE TITLE
Kardinaliteit voor "openingsuren" bij "Contactpunt"

### ISSUE THREAD

**Issue by jensscheerlinck** [Informatievlaanderen/Data.Vlaanderen.be#52]
Kardinaliteit voor "openingsuren" bij "Contactpunt" in het AP Generiek Basis staat momenteel op 0..1.

Om afwijkende openingsuren per dag of per periode mee te kunnen geven moet dit echter 0..* zijn.

Voorbeeld https://schema.org/OpeningHoursSpecification:
```
<script type="application/ld+json">
{
  "@context": "http://schema.org",
  "@type": "Store",
  "name": "Middle of Nowhere Foods",
  "openingHours": "Mo,Tu,We,Th,Fr,Sa,Su 09:00-14:00",
  "openingHoursSpecification":
  [
    {
      "@type": "OpeningHoursSpecification",
      "validFrom": "2013-12-24",
      "validThrough": "2013-12-25",
      "opens": "09:00",
      "closes": "11:00"
    },
    {
      "@type": "OpeningHoursSpecification",
      "validFrom": "2014-01-01",
      "validThrough": "2014-01-01",
      "opens": "12:00",
      "closes": "14:00"
    }
  ]
}
</script>
```

**Comment by DieterDePaepe** [comment]
`openingsuren` is gemapt op `schema:openingHours`. Het verwacht type is verkeerd, want dit zou `String` moeten zijn volgens `schema`.

Issue blijft wel voor `beschikbaarheid` van `Contactpunt`.

**Comment by jensscheerlinck** [comment]
Todo: bij beschikbaarheid moet de kardinaliteit vervangen worden door 0..*

Cf. https://schema.org/OpeningHoursSpecification

Moet ook doorgevoerd worden in Dienstencataloog AP
https://data.vlaanderen.be/doc/applicatieprofiel/dienstencataloog#Contactinfo

**Comment by GeertThijs** [comment]
Aangepast.
