### ISSUE TITLE
Verkeerd type bij Contactpunt:openingsuren

### ISSUE THREAD

**Issue by DieterDePaepe** [Informatievlaanderen/Data.Vlaanderen.be#53]
Schema definieert `openingHours` als een string waarde. Gezien `openingsuren` van `Contactpunt` hierop gemapt is, zou dit ook een String moeten zijn ipv `OpeningsurenSpecificatie`.

Zie ook #52.

**Comment by GeertThijs** [comment]
Is al enige tijd verbeterd.
