### ISSUE TITLE
Hernummering van artikels

### ISSUE THREAD

**Issue by DieterDePaepe** [Informatievlaanderen/Data.Vlaanderen.be#54]
> De nummering van de artikelen is een string; hoe los je een eventuele hernummering op vb. naar aanleiding van een coördinatie, het schrappen van artikelen enz.

Deze vraag werd gesteld op het webinar van het Besluit model.

**Comment by DieterDePaepe** [comment]
Wanneer een bestaand artikel hernummerd wordt omdat het gewijzigd wordt door een nieuw besluit, wordt het conceptueel een nieuw artikel. 
Er kan voor gekozen worden om het nieuwe artikel te zien als een nieuw artikel met nieuw nummer of als een nieuwe versie (temporele variant) van dat bepaald artikel. Bijvoorbeeld het artikel noemde "artikel 2" tot een bepaalde datum en is na wijziging artikel "1bis" geworden.
Het bijhouden van temporele varianten van een artikel heeft de voorkeur.

Beide artikels worden bijgehouden, het onderscheid kan gemaakt worden op basis van de datum.

Er wordt onderscheid gemaakt tussen een conceptuele beslissing en de neergeschreven beslissing. Dit omdat de beslissing uitvoerbaar is los van het feit of het neergeschreven is of niet.
Voordeel van de opsplitsing is dat de beslissing dadelijk rechtsgeldig is terwijl een besluit pas na de zitting neergeschreven wordt, wat de volgende dag kan zijn.

**Comment by brechtvdv** [comment]
Vraag beantwoord, geen impact.
