### ISSUE TITLE
Hoe omgaan met niet stemmende mandatarissen?

### ISSUE THREAD

**Issue by DieterDePaepe** [Informatievlaanderen/Data.Vlaanderen.be#55]
> In een aantal besturen doet het zich voor dat de mandataris toch aanwezig is maar dat hij niet stemt. Dit wordt dan ook zo opgenomen in de notulen. 

Deze vraag werd gesteld tijdens het webinar van het domein Besluit.

**Comment by DieterDePaepe** [comment]
Als een mandataris aanwezig is maar niet stemt, dan dient zijn stem meegeteld te worden bij de onthoudingen. Tijdens de webinar was hierover discussie, we stellen voor om dit apart nog verder uit te klaren.

De vraag is of iemand die blijft zitten tijdens de gemeenteraad en die niet wenst deel te nemen aan de stemming, meegeteld wordt als onthouding of op een andere manier geteld wordt.

**Comment by jensscheerlinck** [comment]
This issue was moved to Informatievlaanderen/OSLO-Discussion#176
