### ISSUE TITLE
Duiding rond "heeft aanwezige" vanuit Mandataris versus vanuit Agendaputn

### ISSUE THREAD

**Issue by DieterDePaepe** [Informatievlaanderen/Data.Vlaanderen.be#56]
> Is het mogelijk om meer duiding te geven bij de relatie 'heeft aanwezige' van de entiteit 'Stemming' naar 'Mandataris' t.o.v. diezelfde soort relatie van 'Behandeling van Agendapunt' naar 'Mandataris'? Kunnen de aanwezigen op de stemming afwijken t.o.v. diegene die aanwezig zijn bij het behandelen van het punt? Een voorbeeld: In geval van belangenvermenging zal de betreffende mandataris niet aanwezig zijn zowel bij het behandelen als op de effectieve stemming?

Deze vraag werd gesteld tijdens het webinar van het domein Besluit.

**Comment by DieterDePaepe** [comment]
Een mandataris zou kunnen aanwezig zijn bij een zitting maar niet bij de behandeling of de stemming van een bepaald punt. Door een link “heeft aanwezige” te voorzien, kan dit op die verschillende punten wijzigen. Zo kan er bijgehouden worden of alle aanwezigen van een stemming gestemd hebben. Vb. in het geval van een geheime stemming. Of bij de behandeling van een agendapunt waarbij een raadslid omwille van een belang de zaal heeft verlaten.

**Comment by jensscheerlinck** [comment]
This issue was moved to Informatievlaanderen/OSLO-Discussion#175
