### ISSUE TITLE
Relatie "heeft stemmer" bij niet stemgerechtigde mandataris

### ISSUE THREAD

**Issue by DieterDePaepe** [Informatievlaanderen/Data.Vlaanderen.be#57]
> In geval dat de mandataris niet stemgerechtigd is, dan zal de relatie 'heeft stemmer' niet bestaan?

Deze vraag werd gesteld tijdens het webinar van het domein Besluit.

**Comment by DieterDePaepe** [comment]
Dit is correct.

**Comment by jensscheerlinck** [comment]
This issue was moved to Informatievlaanderen/OSLO-Discussion#174
