### ISSUE TITLE
Stemming met meer dan 2 keuzes

### ISSUE THREAD

**Issue by DieterDePaepe** [Informatievlaanderen/Data.Vlaanderen.be#58]
> Stel dat er bij een stemming een keuze moet gemaakt worden uit 3 kandidaten. Hoe zien jullie dat ingegeven in het model?

Deze vraag werd gesteld tijdens het webinar van het domein Besluit.

**Comment by DieterDePaepe** [comment]
Een stemming met 3 keuzes kan op 2 manieren opgelost worden. De 3 kandidaten kunnen geïnterpreteerd worden als 3 aparte stemmingen. Waarbij dan duidelijk aangegeven wordt wie voor welke kandidaat stemt en achterliggend moet het programma verifiëren dat er niet op meerdere kandidaten tegelijk gestemd werd.

Het kan ook als stemming gezien worden waarbij we de stemmers weten en het gevolg van de stemming kennen maar dat er niet apart bijgehouden wordt welke mandataris voor welke kandidaat heeft gestemd.

**Comment by jensscheerlinck** [comment]
This issue was moved to Informatievlaanderen/OSLO-Discussion#173
