### ISSUE TITLE
Besluit - wat is citeeropschrift

### ISSUE THREAD

**Issue by DieterDePaepe** [Informatievlaanderen/Data.Vlaanderen.be#59]
> Wat wordt bedoeld met citeeropschrift bij Besluit?

Deze vraag werd gesteld tijdens het webinar van Besluit.

**Comment by DieterDePaepe** [comment]
Het citeeropschrift is de verkorte naam meestal van een decreet of een wet. Deze wordt gebruikt om gemakkelijk naar het decreet of de wet de verwijzen. Deze verkorte naam is ook vermeld in de wet of het decreet.

Een voorbeeld van een citeeropschrift is:

Titel van het decreet:

> Decreet houdende de organisatie van de lokale en provinciale verkiezingen en houdende wijziging van het Gemeentedecreet van 15 juli 2005, het Provinciedecreet van 9 december 2005 en het decreet van 19 december 2008 betreffende de organisatie van de openbare centra voor maatschappelijk welzijn 

Citeeropschrift: 

> het Lokaal en Provinciaal Kiesdecreet van 8 juli 2011

Dit wordt vastgelegd in datzelfde decreet:

> Artikel 5. (04/09/2011- ...)
> Dit decreet wordt aangehaald als : het Lokaal en Provinciaal Kiesdecreet van 8 juli 2011.

**Comment by jensscheerlinck** [comment]
This issue was moved to Informatievlaanderen/OSLO-Discussion#172
