### ISSUE TITLE
Verkiesbaarheidsvoorwaarden opnemen in model?

### ISSUE THREAD

**Issue by DieterDePaepe** [Informatievlaanderen/Data.Vlaanderen.be#60]
> Moet er in het model een link voorzien worden met de verkiesbaarheidsvoorwaarden zoals wonen in de gemeente, Belg zijn, burgerrechten hebben, enz

Deze vraag werd gesteld tijdens het webinar van het domein Mandaat.

**Comment by DieterDePaepe** [comment]
Dit zijn vooral legale argumenten, ze zijn niet bedoeld om gecapteerd te worden in het model. Het zijn regels die vooraf worden afgecheckt. Het wordt pas in het model gecapteerd vanaf dat iemand aangesteld wordt, de controle van de voorwaarden of het goedkeuren van de geloofsbrieven is dan al gebeurd.

**Comment by jensscheerlinck** [comment]
This issue was moved to Informatievlaanderen/OSLO-Discussion#171
