### ISSUE TITLE
Begindatum mandaat tegenover datum eedaflegging

### ISSUE THREAD

**Issue by DieterDePaepe** [Informatievlaanderen/Data.Vlaanderen.be#61]
> Begindatum van de mandataris geeft aan wanneer de mandataris effectief het mandaat opneemt. Dus als de datum van de eedaflegging niet overeenkomt met de datum van de effectieve start van het mandaat, is het de datum van de start van het mandaat die moet ingevuld worden.

> Zijn er nog voorbeelden waarbij de datum van de start verschilt van de eedaflegging?

Deze vraag werd gesteld tijdens het webinar van het domein Mandaat.

**Comment by DieterDePaepe** [comment]
Begindatum van de mandataris geeft aan wanneer de mandataris effectief het mandaat opneemt. Dus als de datum van de eedaflegging niet overeenkomt met de datum van de effectieve start van het mandaat, is het de datum van de start van het mandaat die moet ingevuld worden.

**Comment by jensscheerlinck** [comment]
This issue was moved to Informatievlaanderen/OSLO-Discussion#170
