### ISSUE TITLE
Wat gebeurt er als een mandaat beëindigd wordt?

### ISSUE THREAD

**Issue by DieterDePaepe** [Informatievlaanderen/Data.Vlaanderen.be#62]
> Een mandataris die de status mandaat beëindigd krijgt, verdwijnt die uit het model?

Deze vraag werd gesteld tijdens het webinar van het domein Mandaat.

**Comment by DieterDePaepe** [comment]
Wanneer de status van de mandataris vermeldt dat het mandaat beëindigd werd, verdwijnt dit gegeven niet uit de databank. Deze status geeft aan dat de mandataris niet meer actief is. Hij zal dan niet meer getoond worden maar is nog opvraagbaar met alle gerelateerd gegevens. Door een status mee te geven, laat dit toe om op te vragen wie er in een bepaalde gemeente in een bepaald jaar schepen was van milieu.

**Comment by jensscheerlinck** [comment]
This issue was moved to Informatievlaanderen/OSLO-Discussion#169
