### ISSUE TITLE
Eerste schepen: beleidsdomein of mandaat?

### ISSUE THREAD

**Issue by DieterDePaepe** [Informatievlaanderen/Data.Vlaanderen.be#63]
> Eerste schepen is dit een beleidsdomein of een mandaat?

Deze vraag werd gesteld tijdens het webinar van het domein Mandaat

**Comment by DieterDePaepe** [comment]
Eerste schepen is geen beleidsdomein of mandaat. Het mandaat is schepen. Eerste schepen is de rangorde die hoort bij een mandataris.

**Comment by jensscheerlinck** [comment]
This issue was moved to Informatievlaanderen/OSLO-Discussion#168
