### ISSUE TITLE
codelijsten applicatie profiel generiek

### ISSUE THREAD

**Issue by bertvannuffelen** [Informatievlaanderen/Data.Vlaanderen.be#69]
Beste,

ik bekeek net Geografische Positie en vond daar links naar codelijsten voor de eigenschappen methode en specificatie (zie http://data.vlaanderen.be/doc/applicatieprofiel/generiek#Geografische%20Positie).

Deze verwijzen naar INSPIRE codelijsten. Echter ik heb het gevoel dat deze zowel INSPIRE als adres specifiek zijn en dat dit de genericiteit beperkt.  Deze link zou eigenlijk beter passen in het applicatieprofiel van het adresregister.

Tenslotte kan het zijn dat er voor het adressen-register een eigen codelijst wordt gebruikt die mapped op die INSPIRE codelijst.

Dit is misschien een presentatie issue, maar ik geloof dat dit een algemeen patroon kan zijn.

mvg,

Bert

**Comment by jensscheerlinck** [comment]
This issue was moved to Informatievlaanderen/OSLO-Discussion#167
