### ISSUE TITLE
json-ld context voor generiek

### ISSUE THREAD

**Issue by bertvannuffelen** [Informatievlaanderen/Data.Vlaanderen.be#70]
Beste,

een suggestie: de algemene context van generiek op te splitsen per klasse/subdomein.
Op dit moment begint generiek al verschillende items te bevatten en ik heb het gevoel dat dit vanuit een gebruikersstandpunt een niet zo gemakkelijk te doorgronden verzameling is.

mvg,

Bert

**Comment by jensscheerlinck** [comment]
Besproken met @GeertThijs 

Voorstel om in de documentatie van het AP/VOC (de inleiding en samenvatting) te duiden wat de verschillende logische subdomeinen zijn. Mocht dit in de toekomst nog verder aangroeien kunnen we bekijken om dit nog op te splitsen in subgroepen.

**Comment by GeertThijs** [comment]
De diagrammen werden herschikt zodat de subdomeinen iets beter naar voor komen: Identificatie, Historiek, Locatie, Tijd, FormeelKader & Jurisdictie, Agent & Contactinfo.
