### ISSUE TITLE
Gebruik van locn:Geometry in Generiek

### ISSUE THREAD

**Issue by jensscheerlinck** [Informatievlaanderen/Data.Vlaanderen.be#71]
In het vocabularium Generiek wordt momenteel voor de klasse Geometrie verwezen naar:
http://www.w3.org/ns/locn#Geometry

De huidige versie hiervan in Location Core Vocabulary is "unstable". 

Is het eventueel beter om te werken met:
http://www.opengis.net/ont/sf#Geometry 
of diens superklasse
http://www.opengis.net/ont/geosparql#Geometry

**Comment by jensscheerlinck** [comment]
Met deze wijzigingen blijven ook de domein restricties van http://www.opengis.net/ont/geosparql#asGML en http://www.opengis.net/ont/geosparql#asWKT gerespecteerd.

**Comment by GeertThijs** [comment]
Klinkt logisch maar ik heb er toch nog vragen bij:

- Wat wordt bedoeld met "unstable"? Is dat erg?
- De entiteit locn#Geometry wordt ruimer opgevat dan sf#Geometry of geosparql#Geometry, niet qua definitie maar qua implementatie (dus niet op VOC niveau maar op AP-niveau). Dwz dat ook aan geometrieklassen anders dan deze van Opengis wordt gedacht (W3C, schema.org). En ook gegeocodeerde uri's (bv geoURI) worden als mogelijke implementatie gesuggereerd.
- Anderzijds hebben wij nu net bewust die andere mogelijkheden weg gelaten, kwestie van op INSPIRE af te stemmen.
- Maar tegelijk willen we ook kunnen zeggen dat we op ISA zijn afgestemd.
- De entiteit geosparql#Geometry is wel degelijk het domein van asWkt en asGml, maar is het verboden om ze ook locn#Geometry als domein te geven? Staat nu niet zo in de RDF maar zouden we kunnen toevoegen? Navragen bij Dieter?

**Comment by DieterDePaepe** [comment]
Met "unstable" wil men aangeven dat de termen nog kunnen veranderen. In praktijk lijkt dit echter weinig betekenis te hebben. Zo staat elke term in locn op ofwel `unstable` ofwel `testing`, geen op `stable`. Ook bij FOAF staan er termen als `unstable` aangeduid, maar die gaan nooit meer veranderen... Ik verwacht ook dat de termen in locn niet zomaar gaan veranderen.

In de RDF definities van `locn` wordt geen link gelegd naar `sf` en `geo` of omgekeerd. Echter, in de html documentatie van `locn` wordt er bij de [voorbeelden](https://www.w3.org/ns/locn#locn:geometry) gebruik gemaakt van oa `asWkt`. Conclusie hieruit was dat we: 
- `locn:Geometry` gingen gebruiken voor de afstemming met ISA (we gaven voorrang aan ISA vocs tegenover de geosparql)
- `locn:Geometry` vanuit semantisch standpunt (door de voorbeelden) kan gezien worden als een specialisatie van de `geol:Geometry`. (Ofwel is de documentatie van ISA verkeerd.) Maar gezien het gebruik aan RDF definities, is de overerving er pas als effectief de `asWKT` of `asGML` predicaten gebruikt worden.

Een nadeel van de klassen uit `geo` en `sf`, is dat hun definities simpelweg verwijzen naar niet-publieke ISO standaarden. (Ik had dit issue [al eens vermeld](https://github.com/inspire-eu-rdf/inspire-rdf-guidelines/issues/31) bij Inspire-RDF, die ook van `geo` en `sf` gebruik maken.)

**Comment by GeertThijs** [comment]
Gesloten op basis van bovenstaande argumentatie.
