### ISSUE TITLE
Generiek NAL_Type

### ISSUE THREAD

**Issue by bertvannuffelen** [Informatievlaanderen/Data.Vlaanderen.be#78]
Op https://test.data.vlaanderen.be/doc/applicatieprofiel/generiek

voor FormeelKader is er een type voorzien met als range NAL_type. Dat is gedefinieerd als Skos:Concept. Waarom niet direct een skos:Concept? Of wordt hier gerefereerd naar iets specifieks?

mvg,

Bert

**Comment by GeertThijs** [comment]
Ipv een enumeratie als datatype zouden we inderdaad met een klasse Concept kunnen werken. Echter is het bij UML gebruikelijk om in het geval van een lijst met discrete waarden te werken met een enumeratie. Maw UML verwijst naar de mogelijke range van waarden, ttz naar het ganse ConceptSchema. Enumeraties worden door de EA2RDF converter automatisch omgezet in skos:Concept, dus er lijkt geen echt probleem. Merk ook op dat de standaarden die we maken platformonafhankelijk zijn, dus we modelleren los vh RDF-platform. Als we niet volgens het UML metamodel maar in dat van RDFS/OWL zouden werken zouden we uiteraard wel direct met skos:Concept modelleren.
