### ISSUE TITLE
contactpoint

### ISSUE THREAD

**Issue by bertvannuffelen** [Informatievlaanderen/Data.Vlaanderen.be#79]
De groepering contactInfo is erg restrictief.
Het veronderstelt max 1 email, telefoonnr, ... per contact, maar in de werkelijkheid zijn er veel meer. (cfr organisatie register/relationship management).

Ik stel voor om de cardinaliteiten te laten vallen.

**Comment by bertvannuffelen** [comment]
zie #52

**Comment by jensscheerlinck** [comment]
In Schema.org (waar ContactInfo uit OSLO een vertaling van is) worden deze opgenomen als afzonderlijke instances van ContactInfo ([ContactPoint](https://schema.org/ContactPoint)).

Naar duidelijkheid voor afnemers toe lijkt het mij ook niet onlogisch om te proberen aanhouden dat één contactpunt slechts één e-mail, telefoonnummer... bevat (hoe weet je anders het welke je moet gebruiken?)

Mogelijks moeten we wel wat extra attributen uit Schema.org aanwenden om dit op een semantisch rijke manier te kunnen beschrijven. Ik copy paste even Example 2 uit https://schema.org/ContactPoint

```json
<script type="application/ld+json">
{ "@context" : "http://schema.org",
  "@type" : "Organization",
  "url" : "http://www.t-mobile.com",
  "contactPoint" : [
    { "@type" : "ContactPoint",
      "telephone" : "+1-877-746-0909",
      "contactType" : "customer service",
      "contactOption" : "TollFree",
      "areaServed" : "US"
    } , {
      "@type" : "ContactPoint",
      "telephone" : "+1-505-998-3793",
      "contactType" : "customer service"
    } , {
      "@type" : "ContactPoint",
      "telephone" : "+1-877-296-1018",
      "contactType" : "customer service",
      "contactOption" : ["HearingImpairedSupported","TollFree"] ,
      "areaServed" : "US"
    } , {
      "@type" : "ContactPoint",
      "telephone" : "+1-877-453-1304",
      "contactType" : "technical support",
      "contactOption" : "TollFree",
      "areaServed" : ["US","CA"],
      "availableLanguage" : ["English","French"]
    } , {
      "@type" : "ContactPoint",
      "telephone" : "+1-877-453-1304",
      "contactType" : "bill payment",
      "contactOption" : "TollFree",
      "areaServed" : ["US","CA"]
    } ] }
</script>
```

**Comment by jensscheerlinck** [comment]
This issue was moved to Informatievlaanderen/OSLO-Discussion#166
