### ISSUE TITLE
contactInfo - groepering

### ISSUE THREAD

**Issue by bertvannuffelen** [Informatievlaanderen/Data.Vlaanderen.be#80]
contactInfo verondersteld dat er altijd een groepering is tussen bepaalde contactInfo eigenschappen.
Echter in het organisatieregister is die groepering niet aanwezig.

Er is daar gekozen voor gecontroleerde vrijheid: een beheerder maakt een "kanaal-doel" eigenschap aan en vult dan de waarde in.
b.v. 
  "telefoon kabinet" : "02 232123"
  "email info" : "info@vlaanderen.be"

Dat betekent dat voor dezelfde agent er semantisch verschillende telefoonnummers/email adressen e.d. zijn.

**Comment by jensscheerlinck** [comment]
This issue was moved to Informatievlaanderen/OSLO-Discussion#165
