### ISSUE TITLE
identificator: meer vrijheid

### ISSUE THREAD

**Issue by bertvannuffelen** [Informatievlaanderen/Data.Vlaanderen.be#81]
(cfr test.data.vlaanderen.be) Op dit moment is de eigenschap identificator specifiek gebonden aan 1 datatype.

Ik stel voor om meer flexibileit in te bouwen, en 3 datatypes te definieren.
    a) getypeerde_string idenficator: een string volgens een bepaald type
    b) gestructureerde identificator: unie van {naamruimte, localId, versie)
    c) provenance identificator: provenance info over een identificator in de vorm a) of b)

En het eigenschap identificator als range alle 3 toe te laten.

**Comment by GeertThijs** [comment]
Types a, b en c kunnen teglijk voorkomen. Huidige situatie is dan flexibeler: 1 identificator kan alle types aan. De types a, b en c zijn ook dezelfde identificator, alleen in verschillende vormen (bv al dan niet gestructureerd) en al dan niet met metadata.
