### ISSUE TITLE
provenance object > verduidelijking

### ISSUE THREAD

**Issue by bertvannuffelen** [Informatievlaanderen/Data.Vlaanderen.be#84]
In generiek wordt de entiteit 'object'  met de eigenschap identificator gedefiniëerd.

Hier hebben we nog wel wat verduidelijking nodig:

Het gebouw: http://data.vlaanderen.be/id/gebouw/21312431 is het VAC Gent. 
Er wordt een wijziging gedaan aan de informatie van dit gebouw. Dit levert een nieuwe versie op in het gebouwenregister. Stel dat dit versie v12 is.

Als we dan via een REST service het gebouw ontsluiten wat is dan de waarde van "identificator" ?

--------------------------------------------------------------------
_We tonen het niet_
```
{ 
   "@id" : "http://data.vlaanderen.be/id/gebouw/21312431",
   "naam" : "VAC Gent",
   "status" : "actief"
   ...
}
```
--------------------------------------------------------------------
_we geven de versie mee in de gestructureerde uitsplitsing_
```
{
"@id" : "http://data.vlaanderen.be/id/gebouw/21312431",
   "naam" : "VAC Gent",
   "identificator" : {
       "naamruimte": "http://data.vlaanderen.be/id/gebouw/",
       "localid": "21312431",
       "versie":"v12"
    },
   ...
}
```
------------------------------------------------------------------------
_we geven enkel de versioneerde mee_
```
{
"@id" : "http://data.vlaanderen.be/id/gebouw/21312431/v12",
   "naam" : "VAC Gent",
   "identificator" : {
       "naamruimte": "http://data.vlaanderen.be/id/gebouw/",
       "localid": "21312431",
       "versie":"v12"
    },
   ...
}
```
----------------------------------------------------------------------
_we geven zowel de PURI als de geversioneerde mee als gestructureerde_
```
{
"@id" : "http://data.vlaanderen.be/id/gebouw/21312431",
   "naam" : "VAC Gent",
 "identificator" : {
       "naamruimte": "http://data.vlaanderen.be/id/gebouw/",
       "localid": "21312431",
       "versie": ""
    },
   "identificator" : {
       "naamruimte": "http://data.vlaanderen.be/id/gebouw/",
       "localid": "21312431",
       "versie":"v12"
    },
   ...
}
```
-------------------------------------------------------------------
_we geven de versie mee als een document identifier_
```
{
"@id" : "http://data.vlaanderen.be/id/gebouw/21312431",
   "naam" : "VAC Gent",
 "identificator" : {
       "naamruimte": "http://data.vlaanderen.be/id/gebouw/",
       "localid": "21312431",
       "versie": ""
    },
   "document_identificator" : {
       "naamruimte": "http://data.vlaanderen.be/doc/gebouw/",
       "localid": "21312431",
       "versie":"v12"
    },
   ...
}
```

**Comment by jensscheerlinck** [comment]
This issue was moved to Informatievlaanderen/OSLO-Discussion#164
